default_platform(:ios)

platform :ios do
  desc "Upload App Store Connect metadata only"
  lane :metadata do
    deliver(
      app_identifier: "com.landscapequoteai.app",
      metadata_path: "./fastlane/metadata",
      skip_binary_upload: true,
      skip_screenshots: true,
      submit_for_review: false
    )
  end
end
