import SwiftUI

struct SettingsView: View {
    @Environment(AppSettings.self) private var settings
    @Environment(StoreKitManager.self) private var storeKitManager
    @State private var showingPaywall = false

    var body: some View {
        @Bindable var settings = settings

        Form {
            Section("Business profile") {
                TextField("Business name", text: $settings.businessName)
                    .textInputAutocapitalization(.words)
            }

            Section("Default quote settings") {
                TextField("Default labour rate", value: $settings.defaultLabourRate, format: .number.precision(.fractionLength(0...2)))
                    .keyboardType(.decimalPad)

                TextField("Default profit margin", value: $settings.defaultProfitMargin, format: .number.precision(.fractionLength(0...1)))
                    .keyboardType(.decimalPad)

                TextField("VAT/tax percentage", value: $settings.taxPercentage, format: .number.precision(.fractionLength(0...1)))
                    .keyboardType(.decimalPad)

                Picker("Currency", selection: Binding(
                    get: { settings.currency },
                    set: { settings.currency = $0 }
                )) {
                    ForEach(CurrencyCode.allCases) { currency in
                        Label(currency.title, systemImage: currency.symbol).tag(currency)
                    }
                }
            }

            Section("Subscription") {
                LabeledContent("Status", value: storeKitManager.subscriptionStatusText)

                Button {
                    showingPaywall = true
                } label: {
                    Label(storeKitManager.isPro ? "Manage Pro" : "Upgrade to Pro", systemImage: "crown")
                }
            }

            Section("Privacy and terms") {
                NavigationLink("Privacy policy") {
                    PrivacyPolicyView()
                }

                NavigationLink("Terms") {
                    TermsPlaceholderView()
                }
            }
        }
        .navigationTitle("Settings")
        .sheet(isPresented: $showingPaywall) {
            NavigationStack {
                PaywallView()
            }
        }
    }
}

private struct PrivacyPolicyView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Privacy Policy")
                    .font(.largeTitle.bold())

                privacyBlock(
                    title: "Photos",
                    body: "Site photos are stored locally on this device and are used only to help prepare landscaping estimates. Photo uploads are not sent to an external AI service in this version."
                )

                privacyBlock(
                    title: "Client details",
                    body: "Client names, contact details, site addresses, project notes, and quote totals are stored locally using Apple's on-device persistence."
                )

                privacyBlock(
                    title: "Quote data",
                    body: "Saved estimates, line items, status, PDF exports, and contractor notes remain under your control on this device. Future cloud or AI features should request consent and explain what is transferred."
                )

                privacyBlock(
                    title: "Payments",
                    body: "Subscriptions use Apple's StoreKit in-app purchase flow. The iOS app does not show external payment links."
                )
            }
            .padding(20)
        }
        .background(AppTheme.background.ignoresSafeArea())
        .navigationTitle("Privacy")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func privacyBlock(title: String, body: String) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            Text(title)
                .font(.headline)
            Text(body)
                .font(.body)
                .foregroundStyle(AppTheme.mutedText)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .appCard()
    }
}

private struct TermsPlaceholderView: View {
    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: 16) {
                Text("Terms")
                    .font(.largeTitle.bold())

                Text("These terms explain how estimates are prepared and should be reviewed before being sent to a client.")
                    .font(.body)
                    .foregroundStyle(AppTheme.mutedText)
                    .appCard()

                Text("Quotes generated by the app are estimates and should be reviewed by the contractor before sending to a client. Final project pricing may change after site inspection, access checks, and confirmed materials.")
                    .font(.body)
                    .foregroundStyle(AppTheme.mutedText)
                    .appCard()

                VStack(alignment: .leading, spacing: 8) {
                    Text("Subscriptions")
                        .font(.headline)
                    Text("LandscapeQuote AI uses Apple's standard Terms of Use (EULA) for auto-renewable subscriptions. Subscriptions renew unless cancelled in your Apple ID subscriptions settings.")
                        .font(.body)
                        .foregroundStyle(AppTheme.mutedText)
                    Link("Apple Terms of Use (EULA)", destination: URL(string: "https://www.apple.com/legal/internet-services/itunes/dev/stdeula/")!)
                        .font(.body.weight(.semibold))
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .appCard()
            }
            .padding(20)
        }
        .background(AppTheme.background.ignoresSafeArea())
        .navigationTitle("Terms")
        .navigationBarTitleDisplayMode(.inline)
    }
}
